#!/bin/bash
# by Denny Kroeber / Sarcasm / kroeberd / v.0.2 Beta
#
# https://github.com/kroeberd/automatische-mediatheken-plex/
#
# Define variables
DOCKER_NAME="DOCKER_NAME"  # Replace with the actual name of your Docker container

# To find the token -> https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
PLEX_TOKEN="YOUR_PLEX_TOKEN"  # Replace with your actual Plex token

# Enter the main folder here. the subfolders located there are created as media libraries. E. g. /media
folder_path=r"/media"

# Plex Agent and Scanner
PLEX_AGENT='com.plexapp.agents.stashplexagent'  # Standard Plex Movie Agent
PLEX_SCANNER='Plex Movie Scanner'  # Standard Plex Movie Scanner

# If set to true, then the latest pythonscript is always loaded.
# Default: true
OVERWRITE_OFFLINE_FILE=true

# Only change this value if you know exactly what you are doing. a change is not necessary. 
# Default: http://127.0.0.1:32400
PLEX_URL='http://127.0.0.1:32400'

#####################################
#       Don't change from here      #
#####################################
PYTHON_FILE_URL="https://raw.githubusercontent.com/kroeberd/automatische-mediatheken-plex/main/user.script.version/lib.py"
PYTHON_FILE="lib.py"

# Function to check if apt is available and install pip accordingly
function install_pip() {
    if docker exec "$DOCKER_NAME" which apt &> /dev/null; then
        echo "apt is available. Installing pip using apt..."
        docker exec "$DOCKER_NAME" /bin/bash -c "apt update && apt install python3-pip -y"
    else
        echo "apt is not available. Installing pip using curl..."
        docker exec "$DOCKER_NAME" /bin/bash -c "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py"
        docker exec "$DOCKER_NAME" /bin/bash -c "python3 get-pip.py --break-system-packages"
    fi
    # Install plexapi using pip
    docker exec "$DOCKER_NAME" /bin/bash -c "pip install plexapi --break-system-packages"
}

# Check if pip is installed
echo "Checking if pip is installed..."
if ! docker exec "$DOCKER_NAME" pip --version &> /dev/null; then
    echo "pip is not installed. Installing pip..."
    install_pip
else
    echo "pip is already installed."
fi

# Download the Python file
if [ "$OVERWRITE_OFFLINE_FILE" = true ] || [ ! -f "$PYTHON_FILE" ]; then
    echo "Downloading $PYTHON_FILE..."
    curl -O "$PYTHON_FILE_URL"
else
    echo "$PYTHON_FILE already exists and will not be overwritten."
fi

# Copy and execute the Python script in the Docker container with the Plex token
echo "Copying and running the script in the Docker container..."
docker cp "$PYTHON_FILE" "$DOCKER_NAME":/
docker exec "$DOCKER_NAME" /bin/bash -c "python3 /$PYTHON_FILE $PLEX_TOKEN $folder_path $PLEX_AGENT $PLEX_SCANNER $PLEX_URL"

echo "Script completed."
